name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login the Docker image
      run: docker login -u huydactran1604 -p trandachuy160495

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file microservices-app/jhipster-alerter/Dockerfile --tag my-image-name:$(date +%s)
