name: Shell Command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
  # need checkout before using compose-action
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Start containers
      run: docker-compose -f "app.yml" up -d

