name: Shell Command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
  # need checkout before using compose-action
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup docker-compose
  # You may pin to the exact commit or the version.
  # uses: KengoTODA/actions-setup-docker-compose@1d605d961123cbab67ef2d916746ba4d31413dcb
      uses: KengoTODA/actions-setup-docker-compose@v1.0.9
      with:
    # the version of docker-compose command
        version: latest
    - name: Docker Compose Run Action
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: docker-compose.yml

