name: Shell Command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
  # need checkout before using compose-action
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "docker-compose.yml"

